### ISSUE TITLE
How to install this without Docker

### ISSUE THREAD

**Issue by tomdh76** [VMannello/paperless-email#4]
Thanx for this script. Could you help me to get this to work in a non docker LXC? I am using tteck proxmox scripts (https://tteck.github.io/Proxmox/). I copied all files from your github including pmail_linux to the script folder on the LXC. I then did chmod +X pmail_linux. When I tried to execute the script with ./pmail_linux config.yaml I get an error 'could not load configuration:yaml: line 2: did not find expected key'

**Comment by VinnyHC** [comment]
Sure! Everything you’ve done seems correct. Can you double check that the yaml file you’ve created matches the outline of “sample.yaml” found in the repo? Possibly use a text editor like Sublime or command line tool to ensure your yaml syntax like indents and such are correct?

**Comment by VMannello** [comment]
Absolutely! It seems like you have a formatting error in the yaml configuration file you created.

Can you make sure that it matches the format here:
https://github.com/VMannello/paperless-email/blob/main/sample.yaml

**Comment by VMannello** [comment]
In the simplest layout (one email account and one tag) the yaml should look like this:

`config.yaml`:
```yaml
accounts:
  - name: hotmail
    email: account2@hotmail.com
    smtp:
      server: smtp.live.com
      port: 587
      username: account2@hotmail.com
      password: account2_password
      tls: true

tags:
  simple:
    from: hotmail
    to:
      - "recipient@email.com"
    include_attachment: true
    subject: "paperless processed a file {{ DOCUMENT_FILE_NAME }} | {{ DOCUMENT_CREATED }}"
    body: "Processed {{ DOCUMENT_FILE_NAME }} | Download at: {{ DOCUMENT_DOWNLOAD_URL }}"
```
