### ISSUE TITLE
Script doesn't trigger

### ISSUE THREAD

**Issue by TF1382** [VMannello/paperless-email#5]
Hello and thanks for your effort writing this script.

### I do not get it to run/trigger.

I set up my volume:
```
    volumes:
      ...
      - /home/thomas/paperless/scripts:/usr/src/paperless/scripts
```

added envrionment:
```
environment:
      ...
      PAPERLESS_POST_CONSUME_SCRIPT: "/usr/src/paperless/scripts/pmail /usr/src/paperless/scripts/pmail/config.yaml"
```
Git-Cloned, chmodded 755 and chowned files to thomas:
```
root@paperless:/home/thomas/paperless/scripts/pmail#
-rwxr-xr-x 1 thomas thomas  941  9. Apr 12:22 config.yaml
-rwxr-xr-x 1 thomas thomas   88  9. Apr 12:21 go.mod
-rwxr-xr-x 1 thomas thomas  360  9. Apr 12:21 go.sum
-rwxr-xr-x 1 thomas thomas 1071  9. Apr 12:21 LICENSE
-rwxr-xr-x 1 thomas thomas  486  9. Apr 12:21 main.go
drwxr-xr-x 2 thomas thomas 4096  9. Apr 12:21 pmail
-rwxr-xr-x 1 thomas thomas 3066  9. Apr 12:21 README.md
-rwxr-xr-x 1 thomas thomas 1666  9. Apr 12:21 sample.yaml
```

I changed config.yaml:
```
# define accounts by giving them a name
# to be used in the tag mapping
accounts:
- name: xxx
 email: xxx@yyy.org
 smtp:
   server: mail.yyy.org 
   port: 587
   username: xxx@yyy.org
   password: zzz
   tls: true

# map tags to messages
tags: To-Mail

# all options example
my-tag:
 # account from above
 from: xxx
 # list of recipients
 to:
   - "mail@yyy.org"

 include_attachment: true
 subject: "Paperless mailed you - {{ DOCUMENT_ID }}"
 body: |
   Document:
     - {{ DOCUMENT_FILE_NAME }}
     - {{ DOCUMENT_ID }}
     - {{ DOCUMENT_CREATED }} 
     - {{ DOCUMENT_DOWNLOAD_URL }}
```
--
Finally added files to Paperless, tagged them with "To-Mail", saved but nothing happens...

What am I missing?
